version: '3'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "evertonnascnogueira@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "15432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data 
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge